### ISSUE TITLE
The host IP always appears to be 127.0.0.1

### ISSUE THREAD

**Issue by ghost** [thiagomdiniz/zabbix-google-chat-webhook#4]
In every event notification, the host IP always appears to be [127.0.0.1]

For example:

![image](https://github.com/thiagomdiniz/zabbix-google-chat-webhook/assets/167221350/076ef3a1-456c-410c-9283-fa32974a94f7)

Is this a configuration issue?

**Comment by thiagomdiniz** [comment]
Hi @TeletKeith,

I did some tests here with Zabbix 6.0 and the IP address appears according to the IP address configured on the host interface in Zabbix.

When configuring the media type, the parameter that defines this value is "host_ip". You can confirm that its value is set to the default value "{HOST.IP}".

If everything appears to be OK, could you share some details so I can try to support you?
- What version of Zabbix are you using;
- How is the interface configuration of this host (dev-dra1) in Zabbix;
- Which version of the media type did you import from this repository (v5.0, v6.0, v6.4 or v7.0).
- Also check which version of the media type you imported. This information appears in the description of the media type. Like this:
![image](https://github.com/thiagomdiniz/zabbix-google-chat-webhook/assets/29825093/b961dd7d-f4c5-47bd-a4aa-6da415159289)


Thanks !

**Comment by ghost** [comment]
OK, I understand the situation better now, thanks.
